name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true
  notify-ok:
    name: Telegram success notification
    runs-on: [ubuntu-latest]
    needs: [build]
    if: |
      always() &&
      !contains(needs.*.result, 'skipped') &&
      !contains(needs.*.result, 'failure')
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "все ок"
  notify-fail:
    name: Telegram success notification
    runs-on: [ubuntu-latest]
    needs: [build]
    if: |
      always() &&
      !contains(needs.*.result, 'skipped') &&
      contains(needs.*.result, 'failure')
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Test failed"
